In [21]:
import numpy as np
from numpy import genfromtxt
from sklearn import metrics

In [7]:
raw_data1 = genfromtxt('processed_cleveland.csv', delimiter=',')
raw_data2 = genfromtxt('processed_switzerland.csv', delimiter=',')

raw_data = np.vstack((raw_data1,raw_data2))

In [9]:
raw_data=np.delete(raw_data,[5,11,12],axis=1)

In [10]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
data=imp.fit_transform(raw_data)

In [11]:
X = data[:,:-1]
Y = data[:,-1]

In [12]:
raw_data2=np.delete(raw_data2,[5,11,12],axis=1)

In [13]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
data_T=imp.fit_transform(raw_data2)

In [14]:
X_T = data_T[:,:-1]
Y_T = data_T[:,-1]

In [15]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)

GaussianNB(priors=None)

In [25]:
y_pred=clf.predict(X_T)
print("Number of mislabeled points out of a total %d points : %d" % (X_T.shape[0],(Y_T != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 73


In [26]:
print(metrics.classification_report(Y_T, y_pred))
print(metrics.confusion_matrix(Y_T, y_pred))

             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         8
        1.0       0.43      0.56      0.49        48
        2.0       0.36      0.12      0.19        32
        3.0       0.40      0.63      0.49        30
        4.0       0.00      0.00      0.00         5

avg / total       0.36      0.41      0.36       123

[[ 0  7  0  1  0]
 [ 0 27  5 16  0]
 [ 1 16  4 11  0]
 [ 0 10  1 19  0]
 [ 0  3  1  1  0]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X,Y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [28]:
y_pred=clf.predict(X_T)
print("Number of mislabeled points out of a total %d points : %d" % (X_T.shape[0],(Y_T != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 75


In [29]:
print(metrics.classification_report(Y_T, y_pred))
print(metrics.confusion_matrix(Y_T, y_pred))

             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         8
        1.0       0.40      0.96      0.56        48
        2.0       0.00      0.00      0.00        32
        3.0       0.29      0.07      0.11        30
        4.0       0.00      0.00      0.00         5

avg / total       0.22      0.39      0.25       123

[[ 0  8  0  0  0]
 [ 0 46  0  2  0]
 [ 0 30  0  2  0]
 [ 0 28  0  2  0]
 [ 0  4  0  1  0]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
