In [59]:
import numpy as np
from numpy import genfromtxt

In [60]:
raw_data = genfromtxt('processed_switzerland.csv', delimiter=',')

In [61]:
raw_data=np.delete(raw_data,[5,11,12],axis=1)

In [62]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
data=imp.fit_transform(raw_data)

In [63]:
X = data[:,:-1]
Y = data[:,-1]

In [42]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)

In [85]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)

GaussianNB(priors=None)

In [86]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d" % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 100


In [87]:
print(metrics.classification_report(Y, y_pred))
print(metrics.confusion_matrix(Y, y_pred))

             precision    recall  f1-score   support

        0.0       0.24      1.00      0.38         8
        1.0       0.60      0.12      0.21        48
        2.0       0.00      0.00      0.00        32
        3.0       0.44      0.13      0.21        30
        4.0       0.07      1.00      0.13         5

avg / total       0.36      0.19      0.16       123

[[ 8  0  0  0  0]
 [15  6  0  3 24]
 [ 6  3  0  2 21]
 [ 5  1  0  4 20]
 [ 0  0  0  0  5]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [88]:
print(clf.class_prior_)
print(clf.class_count_)

[0.06504065 0.3902439  0.2601626  0.24390244 0.04065041]
[ 8. 48. 32. 30.  5.]


In [89]:
theta=clf.theta_
print(theta)

[[5.46250000e+01 1.00000000e+00 3.00000000e+00 1.24375000e+02
  0.00000000e+00 5.00000000e-01 1.36625000e+02 1.25000000e-01
  5.37500000e-01 1.75000000e+00]
 [5.56250000e+01 8.75000000e-01 3.66666667e+00 1.27291667e+02
  0.00000000e+00 2.70833333e-01 1.25354167e+02 4.58333333e-01
  4.20833333e-01 1.87500000e+00]
 [5.26250000e+01 9.06250000e-01 3.75000000e+00 1.30000000e+02
  0.00000000e+00 4.06250000e-01 1.26406250e+02 3.75000000e-01
  7.03125000e-01 1.78125000e+00]
 [5.84333333e+01 9.66666667e-01 3.83333333e+00 1.37333333e+02
  0.00000000e+00 4.00000000e-01 1.08200000e+02 5.66666667e-01
  8.23333333e-01 1.86666667e+00]
 [5.20000000e+01 1.00000000e+00 4.00000000e+00 1.20000000e+02
  0.00000000e+00 4.00000000e-01 1.09800000e+02 4.00000000e-01
  9.60000000e-01 1.60000000e+00]]


In [90]:
print(clf.sigma_)

[[9.82343757e+01 6.63874017e-07 5.00000664e-01 6.58984376e+02
  6.63874017e-07 5.00000664e-01 5.81984376e+02 1.09375664e-01
  8.74844414e-01 6.87500664e-01]
 [1.02276042e+02 1.09375664e-01 5.13889553e-01 5.43706598e+02
  6.63874017e-07 2.80816636e-01 5.00978733e+02 2.48264553e-01
  9.25816636e-01 3.59375664e-01]
 [5.48593757e+01 8.49616014e-02 5.62500664e-01 3.39062501e+02
  6.63874017e-07 4.28711601e-01 6.99616212e+02 2.34375664e-01
  1.28342840e+00 2.95899101e-01]
 [5.95788896e+01 3.22228861e-02 2.05556219e-01 5.44555556e+02
  6.63874017e-07 3.06667331e-01 6.39626667e+02 2.45556219e-01
  1.08578955e+00 2.48889553e-01]
 [2.56000007e+01 6.63874017e-07 6.63874017e-07 5.00000007e+01
  6.63874017e-07 2.40000664e-01 4.14560001e+02 2.40000664e-01
  5.46400664e-01 2.40000664e-01]]


In [46]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X,Y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [47]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 74


In [48]:
print(metrics.classification_report(Y, y_pred))
print(metrics.confusion_matrix(Y, y_pred))

             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         8
        1.0       0.41      0.83      0.55        48
        2.0       0.45      0.16      0.23        32
        3.0       0.31      0.13      0.19        30
        4.0       0.00      0.00      0.00         5

avg / total       0.35      0.40      0.32       123

[[ 0  6  1  1  0]
 [ 1 40  3  4  0]
 [ 0 24  5  3  0]
 [ 0 25  1  4  0]
 [ 0  3  1  1  0]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [49]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [50]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 74


In [51]:
print(metrics.classification_report(Y, y_pred))
print(metrics.confusion_matrix(Y, y_pred))

             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         8
        1.0       0.39      1.00      0.56        48
        2.0       1.00      0.03      0.06        32
        3.0       0.00      0.00      0.00        30
        4.0       0.00      0.00      0.00         5

avg / total       0.41      0.40      0.24       123

[[ 0  8  0  0  0]
 [ 0 48  0  0  0]
 [ 0 31  1  0  0]
 [ 0 30  0  0  0]
 [ 0  5  0  0  0]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [81]:
from sklearn.svm import SVC
clf = SVC()
clf.C=1
clf.fit(X, Y)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [82]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 2


In [83]:
print(metrics.classification_report(Y, y_pred))
print(metrics.confusion_matrix(Y, y_pred))

             precision    recall  f1-score   support

        0.0       1.00      0.88      0.93         8
        1.0       0.98      1.00      0.99        48
        2.0       0.97      0.97      0.97        32
        3.0       1.00      1.00      1.00        30
        4.0       1.00      1.00      1.00         5

avg / total       0.98      0.98      0.98       123

[[ 7  0  1  0  0]
 [ 0 48  0  0  0]
 [ 0  1 31  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0  5]]
