In [59]:
import numpy as np
from numpy import genfromtxt

In [60]:
raw_data = genfromtxt('processed_switzerland.csv', delimiter=',')

In [61]:
raw_data=np.delete(raw_data,[5,11,12],axis=1)

In [62]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
data=imp.fit_transform(raw_data)

In [63]:
X = data[:,:-1]
Y = data[:,-1]

In [42]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)

In [85]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)

GaussianNB(priors=None)

In [86]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d" % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 100


             precision    recall  f1-score   support

        0.0       0.24      1.00      0.38         8
        1.0       0.60      0.12      0.21        48
        2.0       0.00      0.00      0.00        32
        3.0       0.44      0.13      0.21        30
        4.0       0.07      1.00      0.13         5

avg / total       0.36      0.19      0.16       123

[[ 8  0  0  0  0]
 [15  6  0  3 24]
 [ 6  3  0  2 21]
 [ 5  1  0  4 20]
 [ 0  0  0  0  5]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [46]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X,Y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [47]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 74


In [48]:
print(metrics.classification_report(Y, y_pred))
print(metrics.confusion_matrix(Y, y_pred))

             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         8
        1.0       0.41      0.83      0.55        48
        2.0       0.45      0.16      0.23        32
        3.0       0.31      0.13      0.19        30
        4.0       0.00      0.00      0.00         5

avg / total       0.35      0.40      0.32       123

[[ 0  6  1  1  0]
 [ 1 40  3  4  0]
 [ 0 24  5  3  0]
 [ 0 25  1  4  0]
 [ 0  3  1  1  0]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [49]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [50]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 74


In [51]:
print(metrics.classification_report(Y, y_pred))
print(metrics.confusion_matrix(Y, y_pred))

             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         8
        1.0       0.39      1.00      0.56        48
        2.0       1.00      0.03      0.06        32
        3.0       0.00      0.00      0.00        30
        4.0       0.00      0.00      0.00         5

avg / total       0.41      0.40      0.24       123

[[ 0  8  0  0  0]
 [ 0 48  0  0  0]
 [ 0 31  1  0  0]
 [ 0 30  0  0  0]
 [ 0  5  0  0  0]]


D:\Programming\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [81]:
from sklearn.svm import SVC
clf = SVC()
clf.C=1
clf.fit(X, Y)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [82]:
y_pred=clf.predict(X)
print("Number of mislabeled points out of a total %d points : %d"
      % (X.shape[0],(Y != y_pred).sum()))

Number of mislabeled points out of a total 123 points : 2


In [83]:
print(metrics.classification_report(Y, y_pred))
print(metrics.confusion_matrix(Y, y_pred))

             precision    recall  f1-score   support

        0.0       1.00      0.88      0.93         8
        1.0       0.98      1.00      0.99        48
        2.0       0.97      0.97      0.97        32
        3.0       1.00      1.00      1.00        30
        4.0       1.00      1.00      1.00         5

avg / total       0.98      0.98      0.98       123

[[ 7  0  1  0  0]
 [ 0 48  0  0  0]
 [ 0  1 31  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0  5]]
